kind: pipeline
type: kubernetes
name: default

workspace:
  base: /src
  path: github.com/xanderflood/payment-scraper

steps:
- name: tags
  image: alpine
  commands:
  - echo -n "build-$${DRONE_BUILD_NUMBER},commit-$${DRONE_COMMIT::8}" > .tags

- name: test
  image: node
  commands:
  - yarn install
  - eslint .

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: xanderflood/payment-scraper
